### ISSUE TITLE
Iban for Vatican City (VA) failing

### ISSUE THREAD

**Issue by desaivishal42** [NaluKit/iban4g#1]
BbanStrucure for VA needs to be added.

**Comment by FrankHossfeld** [comment]
Looks like it is missing.

**Comment by FrankHossfeld** [comment]
Please, can you test it using the HEAD-SNAPSHOT?

**Comment by FrankHossfeld** [comment]
2.0.0-RC4 should land soon ...

**Comment by FrankHossfeld** [comment]
source: https://github.com/arturmkrtchyan/iban4j/issues/66
